// Package beautify implements the "beautify" CLI command.
// It post-processes go tool cover HTML output to inject the shared CSS/JS assets.
package beautify

import (
	"context"
	"crypto/md5"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/peterbourgon/ff/v4"
	"github.com/StevenACoffman/go-beautiful-html-coverage/assets"
	"github.com/StevenACoffman/go-beautiful-html-coverage/cmd/root"
)

// Config holds the configuration for the beautify command.
type Config struct {
	*root.Config

	revision string
	dir      string
}

// New creates and registers the beautify command with the given parent config.
func New(parent *root.Config) *Config {
	cfg := &Config{Config: parent}
	fset := ff.NewFlagSet("beautify").SetParent(parent.Flags)
	fset.StringVar(&cfg.revision, 0, "revision", "", "git revision SHA (required)")
	fset.StringVar(&cfg.dir, 0, "dir", ".", "coverage directory containing the revisions/ subdirectory")
	cmd := &ff.Command{
		Name:      "beautify",
		Usage:     "go-beautiful-html-coverage beautify --revision <sha>",
		ShortHelp: "inject shared CSS/JS assets into go tool cover HTML output",
		LongHelp: `Post-processes the HTML files generated by go tool cover.
Removes the inline <style> and <script> blocks, adds cache-control
meta tags, and injects a <script> tag pointing to the shared index.js.`,
		Flags: fset,
		Exec:  cfg.exec,
	}
	parent.Command.Subcommands = append(parent.Command.Subcommands, cmd)
	return cfg
}

func (cfg *Config) exec(_ context.Context, _ []string) error {
	if cfg.revision == "" {
		return fmt.Errorf("--revision is required")
	}
	return Run(cfg.dir, cfg.revision)
}

// Run beautifies the HTML coverage files for the given revision inside coverDir.
// It modifies revisions/{revision}.html and revisions/{revision}-inc.html in place.
func Run(coverDir, revision string) error {
	hash, err := assetHash()
	if err != nil {
		return fmt.Errorf("compute asset hash: %w", err)
	}

	for _, name := range []string{
		filepath.Join(coverDir, "revisions", revision+".html"),
		filepath.Join(coverDir, "revisions", revision+"-inc.html"),
	} {
		data, err := os.ReadFile(name)
		if err != nil {
			return fmt.Errorf("read %s: %w", name, err)
		}
		out := transformHTML(string(data), hash)
		if err := os.WriteFile(name, []byte(out), 0644); err != nil {
			return fmt.Errorf("write %s: %w", name, err)
		}
	}
	return nil
}

func assetHash() (string, error) {
	css, err := assets.FS.ReadFile("index.css")
	if err != nil {
		return "", err
	}
	js, err := assets.FS.ReadFile("index.js")
	if err != nil {
		return "", err
	}
	h := md5.New()
	h.Write(css)
	h.Write(js)
	return hex.EncodeToString(h.Sum(nil)), nil
}

var (
	styleRe  = regexp.MustCompile(`(?s)\n\t\t<style>.*?</style>`)
	scriptRe = regexp.MustCompile(`(?s)\n\t<script>.*?</script>`)
)

// transformHTML applies the beautify transformations to a single HTML document.
func transformHTML(content, hash string) string {
	content = styleRe.ReplaceAllString(content, "")
	content = scriptRe.ReplaceAllString(content, "")

	// Insert three cache-control meta tags before <title>.
	metas := strings.Join([]string{
		`<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />`,
		"\t\t" + `<meta http-equiv="Pragma" content="no-cache" />`,
		"\t\t" + `<meta http-equiv="Expires" content="0" />`,
		"\t\t",
	}, "\n")
	content = strings.Replace(content, "<title>", metas+"<title>", 1)

	// Inject script tag after </title>.
	content = strings.Replace(content, "</title>",
		"</title>\n\t\t<script src=\"../index.js?"+hash+"\"></script>", 1)

	return content
}
